// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Email struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Email      string
	IsVerified bool
}

type Token struct {
	ID        uuid.UUID
	EmailID   uuid.NullUUID
	Token     string
	CreatedAt time.Time
	ExpiresAt time.Time
	IsUsed    bool
}
