// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (id, email_id, token, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email_id, token, created_at, expires_at, is_used
`

type CreateTokenParams struct {
	ID        uuid.UUID
	EmailID   uuid.NullUUID
	Token     string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createToken,
		arg.ID,
		arg.EmailID,
		arg.Token,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.EmailID,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsUsed,
	)
	return i, err
}
